### ISSUE TITLE
Option to passThrough?

### ISSUE THREAD

**Issue by rikard1979** [nchaulet/httpbackend#7]
I miss the option to passThrough. 

Let say I have configured the browser to use the mocked $httpBackend and still want browser.get to fetch the real resource, but then having all rest-calls made by that path mocked.

I assumed I could then say 
```javascript
backend.whenGET(/^\/#\/clientPath.*/).passThrough();
backend.whenGET(/.*\/my-rest-api\/context.*/).respond(200, {});
```

**Comment by nchaulet** [comment]
I am looking this :)

**Comment by nchaulet** [comment]
passThrough is availlable in version 1.1.0  :)
